version: "3.7"

services:
  hops-localstack:
    image: localstack/localstack:2.0
    container_name: "localstack-demo"
    ports:
      - 4566:4566
    environment:
      - SERVICES=opensearch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=myhost
      - SKIP_SSL_CERT_DOWNLOAD=1
      - OPENSEARCH_DOMAIN=test-domain
      - OPENSEARCH_INDEX=demo-index
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.localstack/init:/etc/localstack/init/ready.d'